### ISSUE TITLE
Error pulling binary on M1 Mac

### ISSUE THREAD

**Issue by mtharrison** [ThousandBirdsInc/chidori#4]
Hey, the project looks very interesting. I tried to install node package on an M1 Mac but got the error:
```
npm ERR! response status 404 Not Found on https://github.com/thousandbirdsinc/chidori/releases/download/v0.1.21/chidori-v0.1.21-node-v108-darwin-arm64-unknown.tar.gz
```

Is it a known issue? Any plans to build a binary for ARM?

**Comment by kvey** [comment]
Known issue! I definitely plan on providing ARM binaries. Releases overall should be in a much better state by end of the week.

**Comment by mtharrison** [comment]
Thanks!

**Comment by kvey** [comment]
Closing due to Chidori having changed substantially
